blank_issues_enabled: true
contact_links:
  - name: ğŸ“– WM_IoT_SDK ç¼–ç¨‹æŒ‡å—
    url: https://doc.winnermicro.net/
    about: é…ç½®å’Œä½¿ç”¨ WM_IoT_SDK çš„æ–‡æ¡£
  - name: ğŸ“– WM_IoT_SDK Programming Guide
    url: https://doc.winnermicro.net/w800/en/latest/
    about: Documentation for configuring and using WM_IoT_SDK
